
repos:

  - repo: local
    hooks:
      - id: find_set_subst
        name: find_set_subst
        entry: ./scripts/find_set_subst.py
        language: system
        always_run: true
        pass_filenames: false

ci:
  autofix_prs: true
  autoupdate_schedule: quarterly
