language: python
python:
  - "3.7"
dist:
  - bionic
services:
  - docker

cache:
  apt: true
  pip: true
  directories:
    # Preserve the output dir for faster build times
    /output
  # How long we should wait for the cache to be fetched before giving up and
  # start without a cache
  timeout: 1000

if: NOT branch =~ /^(cherry-pick-)?backport-\d+-on-/

#addons:
#  apt:
#    packages:
#      - texlive-latex-recommended
#      - texlive-latex-extra
#      - texlive-fonts-recommended

notifications:
  irc:
    channels:
      - "chat.freenode.net#qgis-test"
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    skip_join: true

#  webhooks:
#    urls:
#      - https://webhooks.gitter.im/e/7d967d9679efbbc43466
#    on_success: change  # options: [always|never|change] default: always
#    on_failure: always  # options: [always|never|change] default: always
#    on_start: false     # default: false

#before_install:
#  - mkdir -p $HOME/texlive && curl -L https://github.com/urdh/texlive-blob/releases/download/20150712/texlive.tar.xz | tar -JxC $HOME/texlive

install:
# Sphinx requirements
  - pip3 install -r REQUIREMENTS.txt
# Latex requirements
# maybe later...

#before_script:
#  - ./scripts/ci/setup_git.sh

script:
  - make -f docker.mk doctest

#after_success:
#  - ./scripts/ci/deploy-docs.sh
