|nix|
|win|
|osx|
|action|
|analysis|
|attributes|
|basic_statistics|
|browsebutton|
|buffer|
|calendarwidget|
|checkbox|
|checkbox_checked|
|checkbox_unchecked|
|check_geometry|
|centroids|
|clip|
|color|
|colormap|
|columnview|
|combobox|
|commandlinkbutton|
|convex_hull|
|coordinate_capture|
|copyright_label|
|CRS|
|create_gpx|
|dateedit|
|datetimeedit|
|dbmanager|
|define_projection|
|delaunay|
|delimited_text|
|dem_analysis|
|diagram|
|dial|
|dialogbuttonbox|
|difference|
|digitising|
|dissolve|
|dockwidget|
|doublespinbox|
|dxf2shp_converter|
|edit|
|eliminate|
|event_browser|
|event_id|
|evis_connect|
|evis_file|
|export_geometry|
|export_projection|
|extract_nodes|
|fontcombobox|
|frame|
|ftools|
|fullCumulativeStretch|
|FullHistogramStretch|
|gdal|
|gdal_about|
|gdal_assign_projection|
|gdal_contour|
|gdal_dem|
|gdal_edit|
|gdal_extract_projection|
|gdal_fillnodata|
|gdal_grid|
|gdal_merge|
|gdal_nearblack|
|gdal_polygonize|
|gdal_proximity|
|gdal_raster-clip|
|gdal_raster-overview|
|gdal_raster-paletted|
|gdal_raster-rgb|
|gdal_rasterize|
|gdal_reset|
|gdal_sieve|
|gdal_tileindex|
|gdal_tooltip|
|gdal_translate|
|gdal_vrt|
|gdal_warp|
|general|
|gentlelogo|
|geographic|
|geometry|
|geometrychecker|
|geometrysnapper|
|geoprocessing|
|georeferencer|
|geRasterometry|
|gps_importer|
|gpstrack_barchart|
|gpstrack_polarchart|
|graphicsview|
|grass|
|grass_close_mapset|
|grass_location|
|grass_new_mapset|
|grass_open_mapset|
|grass_region|
|grass_set_region|
|grass_region_edit|
|grass_tools|
|groupbox|
|groupboxcollapsible|
|heatmap|
|histogram|
|hscrollbar|
|hslider|
|hsplit|
|iconAboutConsole|
|iconClassBrowserConsole|
|iconClassConsole|
|iconClassTreeWidgetConsole|
|iconClearConsole|
|iconCloseTabEditorConsole|
|iconCodepadConsole|
|iconCommentEditorConsole|
|iconCopyEditorConsole|
|iconCutEditorConsole|
|iconFileTabsMenuConsole|
|iconFunctionTreeWidgetConsole|
|iconHelpConsole|
|iconHideToolConsole|
|iconIfaceConsole|
|iconMethodTreeWidgetConsole|
|iconNewTabEditorConsole|
|iconOpenConsole|
|iconPasteEditorConsole|
|iconQtCoreConsole|
|iconQtGuiConsole|
|iconRestoreTabsConsole|
|iconRunConsole|
|iconRunScriptConsole|
|iconSaveAsConsole|
|iconSaveConsole|
|iconScriptConsole|
|iconSettingsConsole|
|icon_newgpx|
|icon_dbmanager|
|icon_zonal_statistics|
|import_gpx|
|inputtext|
|interpolation|
|intersect|
|intersections|
|join|
|join_location|
|labels|
|layer_extent|
|locale|
|locked|
|mAction|
|mActionAdd|
|mActionAddAllToOverview|
|mActionAddArrow|
|mActionAddBasicShape|
|mActionAddDelimitedTextLayer|
|mActionAddGCPPoint|
|mActionAddHtml|
|mActionAddImage|
|mActionAddLayer|
|mActionAddLegend|
|mActionAddMap|
|mActionAddMssqlLayer|
|mActionAddNonDbLayer|
|mActionAddOgrLayer|
|mActionAddOracleLayer|
|mActionAddPart|
|mActionAddPostgisLayer|
|mActionAddRasterLayer|
|mActionAddRing|
|mActionAddSpatiaLiteLayer|
|mActionAddWmsLayer|
|mActionAlignBottom|
|mActionAlignHCenter|
|mActionAlignLeft|
|mActionAlignRight|
|mActionAlignTop|
|mActionAlignVCenter|
|mActionAllEdits|
|mActionAnnotation|
|mActionArrowDown|
|mActionArrowLeft|
|mActionArrowRight|
|mActionArrowUp|
|mActionAtlasFirst|
|mActionAtlasLast|
|mActionAtlasNext|
|mActionAtlasPrev|
|mActionAtlasSettings|
|mActionCancelEdits|
|mActionCalculateField|
|mActionCaptureBoundary|
|mActionCaptureCentroid|
|mActionCaptureLine|
|mActionCapturePoint|
|mActionCapturePolygon|
|mActionChangeLabelProperties|
|mActionCheckQgisVersion|
|mActionCollapseTree|
|mActionComposerManager|
|mActionContextHelp|
|mActionCopySelected|
|mActionCustomProjection|
|mActionDeleteAttribute|
|mActionDeleteGCPPoint|
|mActionDeletePart|
|mActionDeleteRing|
|mActionDeleteSelected|
|mActionDeselectAll|
|mActionDraw|
|mActionDupComposer|
|mActionDuplicateLayer|
|mActionEditCopy|
|mActionEditCut|
|mActionEditPaste|
|mActionExpandNewTree|
|mActionExpandTree|
|mActionExportMapServer|
|mActionFileExit|
|mActionFileNew|
|mActionFileOpen|
|mActionFilePrint|
|mActionFileSave|
|mActionFileSaveAs|
|mActionFillRing|
|mActionFilter|
|mActionFolder|
|mActionFormAnnotation|
|mActionFullHistogramStretch|
|mActionGDALScript|
|mActionGroupItems|
|mActionHelpAbout|
|mActionHelpContents|
|mActionHelpSponsors|
|mActionHideAllLayers|
|mActionmIconExpressionEditorOpen|
|mActionIdentify|
|mActionInOverview|
|mActionInvertSelection|
|mActionLabel|
|mActionLabeling|
|mActionLink|
|mActionLinkGeorefToQGis|
|mActionLinkQGisToGeoref|
|mActionLoadGCPpoints|
|mActionLocalHistogramStretch|
|mActionLowerItems|
|mActionMapTips|
|mActionMeasure|
|mActionMeasureAngle|
|mActionMeasureArea|
|mActionMergeFeatAttributes|
|mActionMergeFeatures|
|mActionMoveFeature|
|mActionMoveGCPPoint|
|mActionMoveItemContent|
|mActionMoveItemsToBottom|
|mActionMoveItemsToTop|
|mActionMoveLabel|
|mActionNewAttribute|
|mActionNewBookmark|
|mActionNewComposer|
|mActionNewSpatiaLiteLayer|
|mActionNewVectorLayer|
|mActionNodeTool|
|mActionOffsetCurve|
|mActionOpenRaster|
|mActionOpenTable|
|mActionOptions|
|mActionPan|
|mActionPinLabels|
|mActionProjectProperties|
|mActionPropertyItem|
|mActionQgisHomePage|
|mActionRaiseItems|
|mActionRedo|
|mActionRemove|
|mActionRemoveAllFromOverview|
|mActionRemoveLayer|
|mActionReshape|
|mActionRollbackEdits|
|mActionRotateFeature|
|mActionRotateLabel|
|mActionRotatePointSymbols|
|mActionSaveAsPDF|
|mActionSaveAsSVG|
|mActionSaveEdits|
|mActionSaveGCPpointsAs|
|mActionSaveMapAsImage|
|mActionScaleBar|
|mActionSelect|
|mActionSelectFreehand|
|mActionSelectPan|
|mActionSelectPolygon|
|mActionSelectRadius|
|mActionSelectRectangle|
|mActionSelectedToTop|
|mActionShowAllLayers|
|mActionShowBookmarks|
|mActionShowHideLabels|
|mActionShowPinnedLabels|
|mActionShowPluginManager|
|mActionShowPresets|
|mActionSignMinus|
|mActionSignPlus|
|mActionSimplify|
|mActionSplitFeatures|
|mActionSplitParts|
|mActionStartGeoref|
|mActionTextAnnotation|
|mActionToggleEditing|
|mActionTouch|
|mActionTransformSettings|
|mActionUndo|
|mActionUnGroupItems|
|mActionUnlink|
|mActionUnselectAttributes|
|mActionWhatsThis|
|mActionZoomActual|
|mActionZoomFullExtent|
|mActionZoomIn|
|mActionZoomLast|
|mActionZoomNext|
|mActionZoomOut|
|mActionZoomToLayer|
|mActionZoomToSelected|
|management|
|mapserver_export|
|matrix|
|mean|
|merge_shapes|
|metadata|
|metasearch|
|mGeorefRun|
|mIconAtlas|
|mIconColorBox|
|mIconColorPicker|
|mIconColorSwatches|
|mIconColorWheel|
|mIconDataDefine|
|mIconExpression|
|mIconExpressionSelect|
|mIconImport|
|mIconLock|
|mIconNew|
|mIconProjectionDisabled|
|mIconProjectionEnabled|
|mIconRasterGroup|
|mIconRasterLink|
|mIconStopRendering|
|mIconZip|
|multi_to_single|
|neighbor|
|north_arrow|
|offline_editing_copy|
|offline_editing_sync|
|oracle_raster|
|osm_addRelation|
|osm_createLine|
|osm_createPoint|
|osm_createPolygon|
|osm_createRelation|
|osm_download|
|osm_editRelation|
|osm_featureManager|
|osm_generateTags|
|osm_identify|
|osm_import|
|osm_load|
|osm_move|
|osm_questionMark|
|osm_removeFeat|
|osm_removeTag|
|osm_save|
|osm_upload|
|PanToSelected|
|pencil|
|plugin|
|plugin_installed|
|plugin_installer|
|plugin_upgrade|
|proc_commander|
|proc_history|
|proc_model|
|proc_option|
|proc_result|
|proc_toolbox|
|qgissplash|
|radiobuttonon|
|radiobuttonoff|
|random_points|
|random_selection|
|raster-info|
|raster-interpolate|
|raster-stats|
|raster_terrain|
|regular_points|
|RemoveAllOVerview|
|roadgraph|
|sampling|
|scale_bar|
|selectcolor|
|selectcreatelayer|
|selectnumber|
|selectstring|
|selectesubsetlayer|
|select_location|
|ShowRasterCalculator|
|single_to_multi|
|slider|
|spatialquery|
|spiticon|
|split_layer|
|sub_selection|
|sum_lines|
|sum_points|
|sym_difference|
|symbology|
|simplify|
|tab|
|to_lines|
|topologychecker|
|tracking|
|transformed| 
|union|
|unique|
|unlocked|
|user|
|vector_grid|
|wcs|
|wfs|
