name: Backport
on:
  pull_request_target:
    types:
      - closed
      - labeled

permissions:
  contents: read

jobs:
  backport:
    env:
      BACKPORT_TOKEN: ${{ secrets.BACKPORT_TOKEN }}
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    name: Backport
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@bf7454d06d71f1098171f2acdf0cd4708d7b5920 # v2.20.0
        with:
          disable-sudo-and-containers: true
          egress-policy: block
          allowed-endpoints: >
            api.github.com:443
            github.com:443

      - name: Backport Bot
        id: backport
        uses: m-kuhn/backport@b136a03dc85314c06e342394a581d30b65018916  #v1.2.8
        with:
          github_token: ${{ env.BACKPORT_TOKEN }}
