name: Docs builds

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

on:
  push:
    paths-ignore:
      - 'locale/**'

  pull_request:
    paths-ignore:
      - 'locale/**'

permissions:  # added using https://github.com/step-security/secure-repo
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        format: [html, pdf]

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@bf7454d06d71f1098171f2acdf0cd4708d7b5920 # v2.20.0
        with:
          egress-policy: block
          allowed-endpoints: >
            azure.archive.ubuntu.com:80
            dl.google.com:443
            esm.ubuntu.com:443
            files.pythonhosted.org:443
            github.com:443
            motd.ubuntu.com:443
            packages.microsoft.com:443
            pypi.org:443
            qgis.org:443
      - name: Check out repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 1
      - name: Set up Python 3.14
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: '3.14'
      - name: Install Requirements
        run: |
          if [[ ${{ matrix.format }} != "html" ]]; then
            sudo apt-get update && sudo apt-get install -y texlive-xetex fonts-freefont-otf
          fi

          python -m pip install --upgrade pip
          pip install -r REQUIREMENTS.txt

      - name: Build English ${{ matrix.format }} documentation
        run: |
            make ${{ matrix.format }}
      - name: Upload ${{ matrix.format }} build artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: ${{ matrix.format }} build
          path: build/${{ matrix.format }}
          retention-days: 15
