name:  Pre-commit Checks

on:
  push:
  pull_request:
    branches:
      - master
      - release_*
    paths-ignore:
      - 'locale/**'

  # Allow manual trigger
  workflow_dispatch:

permissions:
  contents: read

jobs:
  # ============================================================================
  # Pre-commit checks (linting, formatting, etc.)
  # ============================================================================
  pre-commit:
    name: Pre-commit Checks
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
      issues: write 

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@fe104658747b27e96e4f7e80cd0a94068e53901d # v2.16.1
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 200
          persist-credentials: true  # We need to persist credentials because of later git push

      - name: Set up Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
            python-version: '3.12'

      - name: Install pre-commit
        run: pip install pre-commit

      - name: Install pre-commit
        run: pip install pre-commit

      - name: Run pre-commit checks
        run: pre-commit run --all-files
